# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timeevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pic', models.URLField(default=False)),
                ('description', models.CharField(default='hi', max_length=200)),
                ('side', models.BooleanField(default=False)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
