# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeevent',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timeevent',
            name='pic',
            field=models.URLField(),
        ),
    ]
