# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20170110_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeevent',
            name='pic',
            field=models.URLField(blank=True),
        ),
    ]
