# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
